"""Derive the registered decision and full descriptive tables from archived rows."""
import argparse
import json
from pathlib import Path

import numpy as np

from v3_gate import CONFIRMATION_SEEDS, GRIDS, LEARNING, paired


def summarize(directory):
    selection = json.loads((directory/'selection.json').read_text())
    learning = json.loads((directory/'confirmation.json').read_text())['rows']
    diagnostic = json.loads((directory/'diagnostic.json').read_text())['rows']

    def values(arm, conditions, metric):
        return [float(np.mean([learning[f'{arm}/{s}'][c][metric] for c in conditions]))
                for s in CONFIRMATION_SEEDS]

    contrasts = {}
    adaptation = {}
    stationary = {}
    for control in ('adam', 'sgd', 'single'):
        contrasts[control] = paired(values(control, LEARNING[2:], 'post_mse'),
                                    values('dual', LEARNING[2:], 'post_mse'))
        adaptation[control] = paired(values(control, LEARNING[2:], 'adaptation_latency'),
                                     values('dual', LEARNING[2:], 'adaptation_latency'))
        stationary[control] = {c: paired(values(control, (c,), 'excess_mse'),
                                         values('dual', (c,), 'excess_mse'))
                               for c in LEARNING[:2]}
    detection = {}
    for condition in next(iter(diagnostic.values())).keys() - {'seconds'}:
        detection[condition] = {}
        for arm in ('single', 'dual'):
            first = diagnostic[str(CONFIRMATION_SEEDS[0])][condition][arm]
            detection[condition][arm] = {
                metric: float(np.mean([diagnostic[str(s)][condition][arm][metric]
                                       for s in CONFIRMATION_SEEDS])) if value is not None else None
                for metric, value in first.items()}
    means = {arm: {c: {metric: float(np.mean(values(arm, (c,), metric)))
                         if value is not None else None
                       for metric, value in learning[f'{arm}/{CONFIRMATION_SEEDS[0]}'][c].items()}
                   for c in LEARNING} for arm in GRIDS}
    detector_pass = all(detection[c]['dual']['block_alarm_rate'] <= .05 for c in LEARNING[:2])
    detector_pass &= all(detection[c]['dual']['event_hit_rate'] >= .8 for c in LEARNING[2:])
    improvement_pass = all(x['treatment'] <= .9 * x['control'] and x['interval95'][1] < 0.
                           for x in contrasts.values())
    retention_pass = all(x['interval95'][1] <= max(.002, .1 * x['control'])
                         for conditions in stationary.values() for x in conditions.values())
    return {'selected': selection['selected'], 'thresholds': selection['thresholds'],
            'detection': detection, 'learning_means': means,
            'post_switch_contrasts': contrasts, 'adaptation_contrasts': adaptation,
            'stationary_contrasts': stationary,
            'decision': {'detector_pass': bool(detector_pass),
                         'improvement_pass': bool(improvement_pass),
                         'retention_pass': bool(retention_pass),
                         'advance': bool(detector_pass and improvement_pass and retention_pass)},
            'confirmation_seconds': {arm: round(sum(learning[f'{arm}/{s}']['seconds']
                                                    for s in CONFIRMATION_SEEDS), 2) for arm in GRIDS}}


def markdown(summary):
    lines = ['# V3 standalone gate: confirmation evidence', '',
             'Generated by `report_v3_gate.py`. 32 independent paired confirmation seeds; '
             'lower error is better. Treatment-minus-control intervals are paired-seed '
             'bootstrap 95% intervals. Decision criteria were committed before execution.', '',
             '## Registered decision', '']
    for key, passed in summary['decision'].items():
        lines.append(f'- {key}: **{"PASS" if passed else "FAIL"}**')
    lines += ['', '## Frozen tuning choices', '',
              '| Arm | Configuration |', '| --- | --- |']
    for arm, config in summary['selected'].items():
        lines.append(f'| {arm} | `{json.dumps(config)}` |')
    lines += ['', 'Each arm used 12 configurations × 8 seeds × 4 streams × 6,000 updates '
              '(2,304,000 updates per arm). Confirmation used 768,000 updates per arm. '
              'Same samples/updates, different arithmetic costs. Adam beta2=.999 and both '
              'gated gains=16 are search-boundary winners; single also selects the lowest '
              'searched rate. The grid does not establish an optimum.', '',
              '## Fixed-observer diagnostics', '',
              '| Condition | Gate | Mean gate | Point alarms | Block alarms | Boundary hit rate | Censored latency |',
              '| --- | --- | ---: | ---: | ---: | ---: | ---: |']
    for condition in LEARNING + ('drift', 'noise_jump'):
        for arm in ('single', 'dual'):
            row = summary['detection'][condition][arm]
            hit = '—' if row['event_hit_rate'] is None else f"{row['event_hit_rate']:.3f}"
            latency = '—' if row['event_latency'] is None else f"{row['event_latency']:.2f}"
            lines.append(f"| {condition} | {arm} | {row['gate_mean']:.5f} | "
                         f"{row['point_alarm_rate']:.5f} | {row['block_alarm_rate']:.5f} | {hit} | {latency} |")
    lines += ['', 'Block false-alarm criteria apply only to stationary quiet/noisy rows. '
              'Only switch_quiet/switch_noisy boundary hits are true target-switch detections. '
              'Drift and noise_jump hits are specificity diagnostics, not successes. '
              'The noise-jump rate averages one upward and one downward noise change. '
              'Thresholds use known noise strata and are not a deployable detector.', '',
              '## Learning by condition', '',
              '| Arm | Condition | Excess MSE | Prediction MSE | Post-switch MSE | Stable MSE | Adaptation latency | Adaptation success | Initial gate | Settled gate |',
              '| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |']
    for arm, conditions in summary['learning_means'].items():
        for condition, metrics in conditions.items():
            fields = ['excess_mse', 'prediction_mse', 'post_mse', 'stable_mse',
                      'adaptation_latency', 'adaptation_success', 'gate_initial', 'gate_settled']
            formatted = ['—' if metrics[f] is None else f'{metrics[f]:.6f}' for f in fields]
            lines.append(f'| {arm} | {condition} | ' + ' | '.join(formatted) + ' |')
    for heading, contrasts in [('Post-switch error', summary['post_switch_contrasts']),
                               ('Adaptation latency', summary['adaptation_contrasts'])]:
        lines += ['', f'## {heading}: dual versus controls', '',
                  '| Control | Control mean | Dual mean | Relative reduction | Difference | 95% interval | Lower-value seeds |',
                  '| --- | ---: | ---: | ---: | ---: | --- | ---: |']
        for arm, row in contrasts.items():
            lo, hi = row['interval95']
            reduction = 100. * (1. - row['treatment'] / row['control'])
            lines.append(f"| {arm} | {row['control']:.6f} | {row['treatment']:.6f} | {reduction:.1f}% | "
                         f"{row['delta']:.6f} | [{lo:.6f}, {hi:.6f}] | {row['lower_error_seeds']}/32 |")
    lines += ['', '## Stationary retention: dual minus controls', '',
              '| Control | Condition | Difference | 95% interval | Allowed upper bound |',
              '| --- | --- | ---: | --- | ---: |']
    for arm, conditions in summary['stationary_contrasts'].items():
        for condition, row in conditions.items():
            lo, hi = row['interval95']
            lines.append(f"| {arm} | {condition} | {row['delta']:.6f} | [{lo:.6f}, {hi:.6f}] | "
                         f"{max(.002, .1 * row['control']):.6f} |")
    lines += ['', '## Cost and limits', '',
              'Active scalar optimizer state including w: SGD 1; Adam 3; single 5; dual 7 '
              '(plus a shared step counter). Diagnostic/output arrays and runner overhead '
              'are additional; this is not a memory benchmark. Confirmation wall time '
              'summed over recorded four-stream rows, after JIT warmup:', '',
              '| Arm | Seconds |', '| --- | ---: |']
    for arm, seconds in summary['confirmation_seconds'].items():
        lines.append(f'| {arm} | {seconds:.2f} |')
    lines += ['', 'Timers are rounded per row to .01 seconds and include stream generation '
              'and scoring, so they cannot resolve small optimizer-cost differences. '
              'This scalar quadratic, fixed timescale, centered-variance implementation '
              'does not represent all nonstationary tasks or variants. No modern-optimizer '
              'superiority, Kalman derivation, or brainsim advantage is established.', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--directory', type=Path, default=Path('results/v3'))
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    summary = summarize(args.directory)
    files = {'summary.json': json.dumps(summary, indent=2, sort_keys=True) + '\n',
             'report.md': markdown(summary)}
    for name, content in files.items():
        path = args.directory/name
        if args.check:
            assert path.read_text() == content, f'stale report: {path}'
        else:
            path.write_text(content)
    print(json.dumps(summary['decision']), flush=True)


if __name__ == '__main__':
    main()
